language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t t.tygreat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true t.tygreat/docker-react npm run test -- --coverage